### ISSUE TITLE
Seed won't generate

### ISSUE THREAD

**Issue by GaryStargazer** [Gilmok/UWNHRando#1]
I keep getting a message that says "Sorry" "nullThis seed failed to successfully generate a ROM."

Doesn't matter what options I pick it always gives me the message.

**Comment by Gilmok** [comment]
I don't have this problem.  I will admit that themes haven't been completely tested but I can almost always generate a ROM with just map randomization.  I'd say just try deleting your .cfg file and run it again with just map randomization.  Let me know if you still have problems.

**Comment by GaryStargazer** [comment]
Thanks for responding,

I tried deleting the .cfg file and didn't touch any of the other tabs. Even leaving the sliders alone at 1 continent, island, etc, and checking nothing but the randomize map box, I still get the issue. Only, now what it does is I click the make ROM button, it stalls for a few seconds, then gives me the aforementioned message, followed by "This seed timed out while generating a ROM. Try a different seed." I tried rerolling the seed over a dozen times and still came to this message.

**Comment by GaryStargazer** [comment]
I want to give an update. I finally got it to make a ROM. It still gives me the two messages above, but it did make one after many attempts. I tried playing it and it seems to work so far, given the character started with a buss and on the east side of the world map.

**Comment by Gilmok** [comment]
I have uploaded an updated version of the randomizer that now generates a MakeLog.txt during ROM generation.  I also increased the ROM generation timeout time from 20 seconds to 2 minutes.  If you still have problems generating ROMs just let me know.  Also, thanks for the star! (Starring this lets me know who uses and likes this rando and helps this to get found easier too)

**Comment by GaryStargazer** [comment]
[UWNHRando-mainmakeLog.txt](https://github.com/Gilmok/UWNHRando/files/6780785/UWNHRando-mainmakeLog.txt)

I've tried again and it made the rom, but it still gave the message about the seed. I've attached the makelog text.

As for the star, absolutely. I made this account just to post here. You have NO idea how happy this randomizer makes me. UWNH is my fave game of all time and I've been praying for a randomizer for years, given I've played the game forward and backwards a hundred times over.

**Comment by Gilmok** [comment]
I looked at the log; this should have successfully generated a ROM.

**Comment by lychees** [comment]
Same issue here. Success after lots of attempts. Thanks!
Is there any source code of the randomizer so that I can invesgate into it further?

**Comment by Gilmok** [comment]
I have uploaded the source code to the rando.  Expensive operations are port placement and possibly map recompression.

**Comment by lychees** [comment]
> I have uploaded the source code to the rando. Expensive operations are port placement and possibly map recompression.

Thank you very much indeed! Very helpful!

**Comment by Eldirans** [comment]
Very excited for this! Unfortunately I am experiencing the "nullThis seed failed to successfully generate a ROM. See makelog for details." error as well. 

I installed it fresh, then located the ROM & checked Randomize Map. No other settings were touched. makeLog.txt is blank. The result is the same on Windows 7 and Windows 10.

**Comment by Eldirans** [comment]
Running the source file in Eclipse, debugging, locating the Rom, checking Randomize Map, then clicking Make ROM gives this error:

> Index -1 out of bounds for length 1
> java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 1
> 	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
> 	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
> 	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
> 	at java.base/java.util.Objects.checkIndex(Objects.java:359)
> 	at java.base/java.util.ArrayList.get(ArrayList.java:427)
> 	at SNESRom.divideString(UWNHRando.java:1414)
> 	at SNESRom.applyTheme(UWNHRando.java:1459)
> 	at SNESRom.randomize(UWNHRando.java:1357)
> 	at RandomizerWindow$RandomizerThread.run(UWNHRando.java:13734)

Hopefully that helps somewhat. Let me know if there is any other info I can provide that would be useful.

**Comment by Gilmok** [comment]
Eldirans it looks like you are using a theme file in your ROM generation.  Could you send me the .thm file you are using?

**Comment by Eldirans** [comment]
There are no .thm files in the UWNHRando-main folder, and the Theme field is blank. Maybe the issue is it is trying to load a theme that isn't there?

EDIT: Pressing the 'Save Theme' button does not appear to do anything, whether the Theme field is blank or I give it a filename.
When debugging, pressing 'Save Theme' gives this error:

> Exception in thread "AWT-EventQueue-0" java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 2
> 	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3751)
> 	at java.base/java.lang.String.substring(String.java:1907)
> 	at RandomizerWindow.saveTheme(UWNHRando.java:14353)
> 	at RandomizerWindow.execute(UWNHRando.java:14319)
> 	at InputLinePanel.actionPerformed(UWNHRando.java:13671)
> 	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
> 	...

**Comment by Gilmok** [comment]
I uploaded a version that will automatically populate (and depopulate) the flags associated with map generation according to the values in the sliders.  This is to prevent a division by 0 error that came up when only selecting "Randomize Map".

**Comment by Eldirans** [comment]
Thanks! With the new version I can see that when following the same process (fresh install, Find Rom, check Randomize Map) it populates the Flags field with MC1I5O2. Unfortunately when I click Make ROM it still gives the same error.

Here is a screenshot of Eclipse with a breakpoint immediately before the error. Interestingly, "in" seems to be filled with garbage characters, whereas on previous breaks it went through 12 different discovery names (Amazon Water Lily, etc.)
![UNWHRandoError](https://user-images.githubusercontent.com/78714665/126251695-83b85d21-e856-44c3-8232-c84a2649feb0.png)

**Comment by Gilmok** [comment]
That "in" parameter is loaded from the theme, and if there is no theme, the game loads in the game original theme.  The theme is supposed to have human readable strings, not garbage like you see above.  My guess is this could be the result of using a 32-bit JVM instead of a 64-bit one, but I am not sure.  If you want to continue to use Eclipse to debug, make sure that the game original theme is loading properly in function SNESRom.getOrigThemeData().

**Comment by Eldirans** [comment]
Just checked and can confirm I am using 64-bit Java. It does appear that on launch, the theme data loaded is partly garbage. The garbage data is added by bytesToText(curr).
![garbage_data_examples](https://user-images.githubusercontent.com/78714665/126367336-6e8d3f11-7fc7-4f36-9259-4aa248f0ff93.png)
Is it possible I am using the wrong version of the rom? I have tried about 4 different downloads to test, all with the same results. I also wonder if I could simply Load Theme from someone else's correct theme data, if that would fix the issue.

**Comment by Gilmok** [comment]
I must have a different version of the ROM than you.  You can email me at ae.armstrong@gmail.com and we can discuss the issue there.

**Comment by MsRileyGuprz** [comment]
Hey Gilmok! From the bottom of my heart, thank you for making this. This has been a dream of mine for years. 

I eventually figured out how to make a ROM (I was missing the base ROM file). However, I can't load the new ROM into the emulator. Whenever I try, it simply boots up the main game. What am I missing?

**Comment by Gilmok** [comment]
The randomizer gives you the option to place the generated ROM in either the randomizer's folder or in the ROM's original folder.  Make sure one of those is checked (one should be checked by default I think).  The randomized ROM will have a bunch of letters and numbers.
